### ISSUE TITLE
HaarCascade.DetectObjects crash after ~10h

### ISSUE THREAD

**Issue by fiorix** [go-opencv/go-opencv#62]
Hi,

I'm observing a weird behavior where some times DetectObjects crash:

```
github.com/lazywei/go-opencv/opencv.(*HaarCascade).DetectObjects(0xc820f48060, 0x7fc0903a0e50, 0x0, 0x0, 0x0)
github.com/lazywei/go-opencv/opencv/cvaux.go:67 +0xf8
```

And some times it works, but when you iterate over the returned `[]*Rect` a call to `.X()` or `.Y()` crashes. In my program, the Haar Cascade is initialized once and re-used for ever, but some times the program is idling for hours (e.g. over night) and as soon as it resumes doing work, it crashes. Maybe something is being garbage collected, not sure... any tips for what to look for?

**Comment by adamdecaf** [comment]
I'm running into this issue also. It seems to be ok often for a few images being processed, but usually under a hundred images or less and then I see this crash. 

Here's a full trace

```
fatal error: 2016/06/19 21:13:55 found 0 faces
unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x2a0d3d0 pc=0x7fa417377093]

runtime stack:
runtime.throw(0x7b6ea0, 0x2a)
	/usr/lib/go/src/runtime/panic.go:527 +0x90 fp=0x7fa4025b2d30 sp=0x7fa4025b2d18
runtime.sigpanic()
	/usr/lib/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0x7fa4025b2d80 sp=0x7fa4025b2d30

goroutine 78 [syscall, locked to thread]:
runtime.cgocall(0x405f40, 0xc820029448, 0xc800000000)
	/usr/lib/go/src/runtime/cgocall.go:120 +0x11b fp=0xc8200293f0 sp=0xc8200293c0
github.com/lazywei/go-opencv/opencv._Cfunc_cvHaarDetectObjects(0xc8200d4090, 0x242db90, 0x7fa3fc000e90, 0x3ff199999999999a, 0x100000003, 0x0, 0x0, 0x0)
	??:0 +0x3d fp=0xc820029448 sp=0xc8200293f0
github.com/lazywei/go-opencv/opencv.(*HaarCascade).DetectObjects(0xc820029688, 0xc8200d4090, 0x0, 0x0, 0x0)
	/home/adam/src/go/src/github.com/lazywei/go-opencv/opencv/cvaux.go:67 +0xf8 fp=0xc8200294e0 sp=0xc820029448
main.detectFaces(0x242db90, 0x90, 0x4, 0x42475200000008, 0x41524742, 0x400000000, 0x1e0000002c0, 0x0, 0x0, 0x0, ...)
	/home/adam/src/go/src/github.com/adamdecaf/cameras/detect.go:45 +0x7f fp=0xc820029688 sp=0xc8200294e0
main.detect(0x242db90, 0x90, 0x4, 0x42475200000008, 0x41524742, 0x400000000, 0x1e0000002c0, 0x0, 0x0, 0x0, ...)
	/home/adam/src/go/src/github.com/adamdecaf/cameras/detect.go:41 +0x5b fp=0xc820029728 sp=0xc820029688
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820029730 sp=0xc820029728
created by main.DetectFaces
	/home/adam/src/go/src/github.com/adamdecaf/cameras/detect.go:30 +0x2f1

goroutine 1 [chan receive]:
runtime.gopark(0x7ddca8, 0xc82006c178, 0x75b340, 0xc, 0x17, 0x3)
	/usr/lib/go/src/runtime/proc.go:185 +0x163 fp=0xc82003faa0 sp=0xc82003fa78
runtime.goparkunlock(0xc82006c178, 0x75b340, 0xc, 0x7dda17, 0x3)
	/usr/lib/go/src/runtime/proc.go:191 +0x54 fp=0xc82003fad8 sp=0xc82003faa0
runtime.chanrecv(0x6733e0, 0xc82006c120, 0xc82003fe48, 0xc82003fb01, 0x400000)
	/usr/lib/go/src/runtime/chan.go:448 +0x472 fp=0xc82003fb98 sp=0xc82003fad8
runtime.chanrecv2(0x6733e0, 0xc82006c120, 0xc82003fe48, 0x90)
	/usr/lib/go/src/runtime/chan.go:354 +0x2b fp=0xc82003fbc8 sp=0xc82003fb98
main.DetectFaces(0xc82006c120)
	/home/adam/src/go/src/github.com/adamdecaf/cameras/detect.go:27 +0x280 fp=0xc82003fee0 sp=0xc82003fbc8
main.main()
	/home/adam/src/go/src/github.com/adamdecaf/cameras/main.go:31 +0x276 fp=0xc82003ff60 sp=0xc82003fee0
runtime.main()
	/usr/lib/go/src/runtime/proc.go:111 +0x2b0 fp=0xc82003ffb0 sp=0xc82003ff60
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82003ffb8 sp=0xc82003ffb0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82003efb8 sp=0xc82003efb0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x7ddca8, 0xaeaf10, 0x75c840, 0xf, 0x14, 0x1)
	/usr/lib/go/src/runtime/proc.go:185 +0x163 fp=0xc82002a758 sp=0xc82002a730
runtime.goparkunlock(0xaeaf10, 0x75c840, 0xf, 0xc820000114, 0x1)
	/usr/lib/go/src/runtime/proc.go:191 +0x54 fp=0xc82002a790 sp=0xc82002a758
runtime.forcegchelper()
	/usr/lib/go/src/runtime/proc.go:152 +0xb8 fp=0xc82002a7c0 sp=0xc82002a790
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002a7c8 sp=0xc82002a7c0
created by runtime.init.4
	/usr/lib/go/src/runtime/proc.go:141 +0x2b

goroutine 3 [GC sweep wait]:
runtime.gopark(0x7ddca8, 0xaeb080, 0x757ae0, 0xd, 0x456914, 0x1)
	/usr/lib/go/src/runtime/proc.go:185 +0x163 fp=0xc82002af48 sp=0xc82002af20
runtime.goparkunlock(0xaeb080, 0x757ae0, 0xd, 0x14, 0x1)
	/usr/lib/go/src/runtime/proc.go:191 +0x54 fp=0xc82002af80 sp=0xc82002af48
runtime.bgsweep(0xc820062000)
	/usr/lib/go/src/runtime/mgcsweep.go:67 +0x14d fp=0xc82002afb8 sp=0xc82002af80
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002afc0 sp=0xc82002afb8
created by runtime.gcenable
	/usr/lib/go/src/runtime/mgc.go:206 +0x53

goroutine 18 [finalizer wait]:
runtime.gopark(0x7ddca8, 0xb0ff10, 0x75c430, 0xe, 0x14, 0x1)
	/usr/lib/go/src/runtime/proc.go:185 +0x163 fp=0xc820026718 sp=0xc8200266f0
runtime.goparkunlock(0xb0ff10, 0x75c430, 0xe, 0x14, 0x1)
	/usr/lib/go/src/runtime/proc.go:191 +0x54 fp=0xc820026750 sp=0xc820026718
runtime.runfinq()
	/usr/lib/go/src/runtime/mfinal.go:154 +0xaa fp=0xc8200267c0 sp=0xc820026750
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200267c8 sp=0xc8200267c0
created by runtime.createfing
	/usr/lib/go/src/runtime/mfinal.go:135 +0x60

goroutine 19 [runnable]:
image.(*YCbCr).At(0xc8200c0100, 0x13e, 0xc6, 0x4066400000000000, 0x4065e00000000000)
	/usr/lib/go/src/image/ycbcr.go:70 fp=0xc820041e18 sp=0xc820041e10
github.com/lazywei/go-opencv/opencv.FromImage(0x7fa4183d4960, 0xc8200c0100, 0xc8203aa050)
	/home/adam/src/go/src/github.com/lazywei/go-opencv/opencv/goimage.go:29 +0x11e fp=0xc820041ef0 sp=0xc820041e18
main.downloadUrl(0x7ffdb1a8e272, 0x28, 0xc82006c120)
	/home/adam/src/go/src/github.com/adamdecaf/cameras/download.go:40 +0x2b6 fp=0xc820041f98 sp=0xc820041ef0
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820041fa0 sp=0xc820041f98
created by main.main
	/home/adam/src/go/src/github.com/adamdecaf/cameras/main.go:24 +0x224

goroutine 22 [Concurrent GC wait]:
runtime.gopark(0x7ddca8, 0xaeb060, 0x786ec0, 0x12, 0xc820027d14, 0x1)
	/usr/lib/go/src/runtime/proc.go:185 +0x163 fp=0xc820027f58 sp=0xc820027f30
runtime.goparkunlock(0xaeb060, 0x786ec0, 0x12, 0x10014, 0x1)
	/usr/lib/go/src/runtime/proc.go:191 +0x54 fp=0xc820027f90 sp=0xc820027f58
runtime.backgroundgc()
	/usr/lib/go/src/runtime/mgc.go:900 +0x8b fp=0xc820027fc0 sp=0xc820027f90
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820027fc8 sp=0xc820027fc0
created by runtime.startGC
	/usr/lib/go/src/runtime/mgc.go:870 +0x186

goroutine 34 [timer goroutine (idle)]:
runtime.gopark(0x7ddca8, 0xaeb0e0, 0x792c60, 0x16, 0x14, 0x1)
	/usr/lib/go/src/runtime/proc.go:185 +0x163 fp=0xc820026f00 sp=0xc820026ed8
runtime.goparkunlock(0xaeb0e0, 0x792c60, 0x16, 0x14, 0x1)
	/usr/lib/go/src/runtime/proc.go:191 +0x54 fp=0xc820026f38 sp=0xc820026f00
runtime.timerproc()
	/usr/lib/go/src/runtime/time.go:202 +0x123 fp=0xc820026fc0 sp=0xc820026f38
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820026fc8 sp=0xc820026fc0
created by runtime.addtimerLocked
	/usr/lib/go/src/runtime/time.go:116 +0x11f

goroutine 20 [select]:
runtime.gopark(0x7ddce0, 0xc820040ed8, 0x754560, 0x6, 0x18, 0x2)
	/usr/lib/go/src/runtime/proc.go:185 +0x163 fp=0xc820040b98 sp=0xc820040b70
runtime.selectgoImpl(0xc820040ed8, 0x0, 0x18)
	/usr/lib/go/src/runtime/select.go:392 +0xa64 fp=0xc820040d40 sp=0xc820040b98
runtime.selectgo(0xc820040ed8)
	/usr/lib/go/src/runtime/select.go:212 +0x12 fp=0xc820040d60 sp=0xc820040d40
net/http.(*persistConn).readLoop(0xc8200de000)
	/usr/lib/go/src/net/http/transport.go:976 +0xac7 fp=0xc820040fa8 sp=0xc820040d60
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820040fb0 sp=0xc820040fa8
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:685 +0xc78

goroutine 21 [select]:
runtime.gopark(0x7ddce0, 0xc8200faf10, 0x754560, 0x6, 0x18, 0x2)
	/usr/lib/go/src/runtime/proc.go:185 +0x163 fp=0xc8200fac78 sp=0xc8200fac50
runtime.selectgoImpl(0xc8200faf10, 0x0, 0x18)
	/usr/lib/go/src/runtime/select.go:392 +0xa64 fp=0xc8200fae20 sp=0xc8200fac78
runtime.selectgo(0xc8200faf10)
	/usr/lib/go/src/runtime/select.go:212 +0x12 fp=0xc8200fae40 sp=0xc8200fae20
net/http.(*persistConn).writeLoop(0xc8200de000)
	/usr/lib/go/src/net/http/transport.go:1009 +0x40c fp=0xc8200fafa8 sp=0xc8200fae40
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200fafb0 sp=0xc8200fafa8
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:686 +0xc9d

goroutine 23 [mark worker (idle)]:
runtime.gopark(0x7ddb40, 0xc8200b4000, 0x78fc80, 0x12, 0x14, 0x0)
	/usr/lib/go/src/runtime/proc.go:185 +0x163 fp=0xc820028750 sp=0xc820028728
runtime.gcBgMarkWorker(0xc82001e000)
	/usr/lib/go/src/runtime/mgc.go:1289 +0xf7 fp=0xc8200287b8 sp=0xc820028750
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200287c0 sp=0xc8200287b8
created by runtime.gcBgMarkStartWorkers
	/usr/lib/go/src/runtime/mgc.go:1239 +0x93

goroutine 50 [mark worker (idle)]:
runtime.gopark(0x7ddb40, 0xc820031200, 0x78fc80, 0x12, 0x14, 0x0)
	/usr/lib/go/src/runtime/proc.go:185 +0x163 fp=0xc8204f0750 sp=0xc8204f0728
runtime.gcBgMarkWorker(0xc82001f500)
	/usr/lib/go/src/runtime/mgc.go:1289 +0xf7 fp=0xc8204f07b8 sp=0xc8204f0750
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8204f07c0 sp=0xc8204f07b8
created by runtime.gcBgMarkStartWorkers
	/usr/lib/go/src/runtime/mgc.go:1239 +0x93

goroutine 51 [mark worker (idle)]:
runtime.gopark(0x7ddb40, 0xc8200b4000, 0x78fc80, 0x12, 0x14, 0x0)
	/usr/lib/go/src/runtime/proc.go:185 +0x163 fp=0xc8204f0f50 sp=0xc8204f0f28
runtime.gcBgMarkWorker(0xc820020a00)
	/usr/lib/go/src/runtime/mgc.go:1289 +0xf7 fp=0xc8204f0fb8 sp=0xc8204f0f50
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8204f0fc0 sp=0xc8204f0fb8
created by runtime.gcBgMarkStartWorkers
	/usr/lib/go/src/runtime/mgc.go:1239 +0x93

goroutine 52 [mark worker (idle)]:
runtime.gopark(0x7ddb40, 0xc8200b4480, 0x78fc80, 0x12, 0x14, 0x0)
	/usr/lib/go/src/runtime/proc.go:185 +0x163 fp=0xc8204f1750 sp=0xc8204f1728
runtime.gcBgMarkWorker(0xc820022000)
	/usr/lib/go/src/runtime/mgc.go:1289 +0xf7 fp=0xc8204f17b8 sp=0xc8204f1750
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8204f17c0 sp=0xc8204f17b8
created by runtime.gcBgMarkStartWorkers
	/usr/lib/go/src/runtime/mgc.go:1239 +0x93
Aborted (core dumped)
```

**Comment by adamdecaf** [comment]
Small update. I was running `DetectObjects` inside multiple concurrent goroutines and tried running them as a single threaded detection and seem to be avoiding some aspect of the segfaults.

The other thing I noticed was that Rect's `Height()` and `Width()` functions can be a cause of segfaults. It seems to be something with the cast on the unexported .height and .width properties.

**Comment by fiorix** [comment]
¯\_(ツ)_/¯
